"""habit_edit

Revision ID: 584a4ff0f936
Revises: 711e336d4cb0
Create Date: 2024-09-22 21:44:25.373346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584a4ff0f936'
down_revision: Union[str, None] = '711e336d4cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('result', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'result')
    # ### end Alembic commands ###
