version: '3.2'
services:

  postgres:

    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=db_bots
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data

